language: php

sudo: true

php:
  - 5.5.9
#  - 5.6
#  - 5.6
#  - 7.0
#  - hhvm

addons:
  hosts:
    - tutorschool.dev

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_DISCARD_CHANGES=true
    - COMPOSER_NO_INTERACTION=1
    - COMPOSER_DISABLE_XDEBUG_WARN=1

before_install:
  # set GitHub token and update composer
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer self-update && composer -V
#  - export USE_ZEND_ALLOC=0

install:
  # install Composer dependencies
  - rm composer.lock
  # these providers require referencing git commit's which cause Travis to fail
  - sed -i '/mollie/d' composer.json
  - sed -i '/2checkout/d' composer.json
  - travis_retry composer install --prefer-dist;

before_script:
  # prevent MySQL went away error
  - mysql -u root -e 'SET @@GLOBAL.wait_timeout=28800;'
  # copy configuration files
  - cp .env.example .env
  - cp tests/_bootstrap.php.default tests/_bootstrap.php
  - php artisan key:generate --no-interaction
  - sed -i 's/APP_ENV=production/APP_ENV=development/g' .env
  - sed -i 's/APP_DEBUG=false/APP_DEBUG=true/g' .env
  - sed -i '$a TUTOR_DEV=true' .env
  - sed -i '$a TRAVIS=true' .env
  # create the database and user
  - mysql -u root -e "create database IF NOT EXISTS tutorschool;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON tutorschool.* To 'tutor'@'localhost' IDENTIFIED BY 'tutorsecret'; FLUSH PRIVILEGES;"
  # migrate and seed the database
  - php artisan migrate --no-interaction
  - php artisan db:seed --no-interaction # default seed
  - php artisan db:seed --no-interaction --class=UsersTableSeeder # development seed
  # Start webserver on tutorschool.dev:8000
  - php artisan serve --host=tutorschool.dev --port=8000 & # '&' allows to run in background
  # Start PhantomJS
  - phantomjs --webdriver=4444 & # '&' allows to run in background
  # Give it some time to start
  - sleep 5
  # Make sure the app is up-to-date
  #- curl -L http://tutorschool.dev:8000/update

script:
  - php ./vendor/codeception/codeception/codecept run --debug acceptance AllPagesCept.php
  #- php ./vendor/codeception/codeception/codecept run --debug acceptance StudentCest.php


after_script:
  - cat .env
  #- mysql -u root -e 'select * from students;' tutorschool

  - cat storage/logs/laravel-error.log
  - cat storage/logs/laravel-info.log

notifications:
  email:
    on_success: never
    on_failure: change
